// src/components/Dropdown/DropdownMenuButton.vue
<script setup lang="ts">
import type { FunctionalComponent, HTMLAttributes, VNodeProps } from 'vue';

interface DropdownMenuButtonProps {
	/**
	 * Optional Heroicon element, to prepend (left) or append (right) to menu link.
	 */
	icon?: FunctionalComponent<HTMLAttributes & VNodeProps>;
	/**
	 * Align the icon on the left or right side of the menu link.
	 */
	alignIcon?: 'left' | 'right';
	className?: string;
	onClick?: () => void;
}

const props = defineProps<DropdownMenuButtonProps>();

const handleClick = (e: Event) => {
	const $target = e.target as HTMLLinkElement;
	$target.closest('.dropdown')?.removeAttribute('open');

	if (props.onClick) {
		props.onClick();
	}
};
</script>

<template>
	<button
		:className="
			`dropdown-menu-item ${icon ? `has-icon align-icon--${alignIcon}` : ''} ${className}`.trim()
		"
		:onClick="handleClick"
		type="button"
	>
		<component :is="props.icon" v-if="props.icon && alignIcon === 'left'" />
		<span><slot></slot></span>
		<component :is="props.icon" v-if="props.icon && alignIcon === 'right'" />
	</button>
</template>

// src/components/Dropdown/DropdownMenuButton.tsx
import React from 'react';

interface DropdownMenuButtonProps {
	children: React.ReactNode;
	/**
	 * Optional Heroicon element, to prepend (left) or append (right) to menu link.
	 */
	icon?: React.ReactElement;
	/**
	 * Align the icon on the left or right side of the menu link.
	 */
	alignIcon?: 'left' | 'right';
	className?: string;
	onClick?(): void;
}

/**
 * A `<Button>` element inside a dropdown menu.
 */
export const DropdownMenuButton = ({
	children,
	icon = undefined,
	alignIcon = 'left',
	className = '',
	onClick = undefined,
}: DropdownMenuButtonProps) => {
	const handleClick = (e: React.SyntheticEvent) => {
		const $target = e.nativeEvent.target as HTMLLinkElement;
		$target.closest('.dropdown')?.removeAttribute('open');

		if (onClick) {
			onClick();
		}
	};

	return (
		<button
			className={`dropdown-menu-item ${icon ? `has-icon align-icon--${alignIcon}` : ''} ${className}`.trim()}
			onClick={handleClick}
			type="button"
		>
			{icon && alignIcon === 'left' && icon}
			<span>{children}</span>
			{icon && alignIcon === 'right' && icon}
		</button>
	);
};
