// src/components/Panel/ClosablePanel.tsx
import React from 'react';
import { XMarkIcon } from '@heroicons/react/24/solid';
import { Button } from '../Button';
import { Panel } from './Panel';
import { PanelHeader } from './PanelHeader';
import { PanelActions } from './PanelActions';
import { PanelTitleWrapper } from './PanelTitleWrapper';
import { PanelBody } from './PanelBody';

interface ClosablePanelProps {
	children: React.ReactNode;
	onClose: () => void;
	title: React.ReactNode;
	/**
	 * Controls whether the panel body has internal padding.
	 */
	padded?: boolean;
	actions?: React.ReactNode;
}

const ClosablePanel = ({
	children,
	onClose,
	title,
	padded = true,
	actions = undefined,
}: ClosablePanelProps) => (
	<Panel>
		<PanelHeader>
			<PanelTitleWrapper>{title}</PanelTitleWrapper>
			<PanelActions>
				{actions}
				<Button onClick={onClose} color="red" title="Close this panel">
					<XMarkIcon className="icon" />
				</Button>
			</PanelActions>
		</PanelHeader>
		<PanelBody padded={padded}>{children}</PanelBody>
	</Panel>
);

export { ClosablePanel };

// src/components/Panel/ClosablePanel.vue
<script setup lang="ts">
import { XMarkIcon } from '@heroicons/vue/24/solid';
import CustomButton from '../CustomButton.vue';
import Panel from './Panel.vue';
import PanelHeader from './PanelHeader.vue';
import PanelActions from './PanelActions.vue';
import PanelTitleWrapper from './PanelTitleWrapper.vue';
import PanelTitleTags from './PanelTitleTags.vue';
import PanelBody from './PanelBody.vue';
import type { FunctionalComponent, HTMLAttributes, VNodeProps } from 'vue';

interface ClosablePanelProps {
	onClose: () => void;
	title: FunctionalComponent<HTMLAttributes & VNodeProps>;
	tags?: FunctionalComponent<HTMLAttributes & VNodeProps>;
	/**
	 * Controls whether the panel body has internal padding.
	 */
	padded?: boolean;
	actions?: FunctionalComponent<HTMLAttributes & VNodeProps>;
}

const {
	onClose,
	title,
	tags = undefined,
	padded = true,
	actions = undefined,
} = defineProps<ClosablePanelProps>();
</script>

<template>
	<Panel>
		<PanelHeader>
			<PanelTitleWrapper><component :is="title" /></PanelTitleWrapper>
			<PanelTitleTags v-if="tags"><component :is="tags" /> </PanelTitleTags>
			<PanelActions>
				<component :is="actions" v-if="actions" />
				<CustomButton :on-click="onClose" color="red" title="Close this panel">
					<XMarkIcon class="icon" />
				</CustomButton>
			</PanelActions>
		</PanelHeader>
		<PanelBody :padded="padded"><slot></slot></PanelBody>
	</Panel>
</template>
