// src/components/Panel/PanelBody.tsx
import React from 'react';

interface PanelBodyProps {
  children: React.ReactNode;
  className?: string;
  fill?: boolean;
}

export const PanelBody = ({
  children,
  className = '',
  fill = true,
}: PanelBodyProps) => (
  <div className={`panel-body ${fill ? 'panel-body--fill' : ''} ${className}`.trim()}>
    {children}
  </div>
);

// src/components/Panel/PanelBody.vue
<script setup lang="ts">
interface PanelBodyProps {
	className?: string;
	padded?: boolean;
}

const { className = '', padded = true } = defineProps<PanelBodyProps>();
</script>

<template>
	<div
		:class="
			`panel-body ${padded ? 'panel-body--padded' : ''} ${className}`.trim()
		"
	>
		<slot></slot>
	</div>
</template>
