// oldSrc/components/Panel/PanelHeader.tsx
import React from 'react';

interface PanelHeaderProps {
	children: React.ReactNode;
	/**
	 * Controls whether the panel body has internal padding.
	 */
	padded?: boolean;
	className?: string;
}

export const PanelHeader = ({
	children,
	className = '',
	padded = true,
}: PanelHeaderProps) => (
	<div
		className={`panel-header ${padded ? 'panel-header--padded' : ''} ${className}`.trim()}
	>
		{children}
	</div>
);

// apps/bulk-uploader/src/components/Panel/PanelHeader.vue
<script setup lang="ts">
interface PanelHeaderProps {
	className?: string;
	padded?: boolean;
}

const { className = '', padded = true } = defineProps<PanelHeaderProps>();
</script>

<template>
	<div
		:class="
			`panel-header ${padded ? 'panel-header--padded' : ''} ${className}`.trim()
		"
	>
		<slot></slot>
	</div>
</template>
