// src/components/PanelGrid/PanelGrid.vue
<script setup lang="ts">
interface PanelGridProps {
	/**
	 * Makes the first panel sized properly for a sidebar.
	 * Doesn't require any additional markup on the sidebar panel.
	 */
	sidebarred?: boolean;
	className?: string;
}

const { sidebarred = false, className = '' } = defineProps<PanelGridProps>();
</script>

<template>
	<div
		:class="`panel-grid ${sidebarred ? 'sidebarred' : ''} ${className}`.trim()"
	>
		<slot></slot>
	</div>
</template>

<style>
.panel-grid {
	position: absolute;
	inset: 0;

	display: grid;
	grid: auto / auto-flow 1fr;
	gap: 10px;

	transition: grid 100ms;
}

.panel-grid.sidebarred {
	/* Expressed as a CSS variable for future-proofing.
     E.g., we can have a "closed sidebar" just by setting this variable
     narrower with `.panel-grid.sidebarred.closed` or something,
     without repeating our entire grid definition. */
	--sidebar--width: clamp(250px, 20%, 500px);

	grid: auto / var(--sidebar--width) repeat(auto-fit, minmax(0, 1fr));
}

.panel-grid-item {
	position: relative;
}

.panel-grid-item .panel {
	position: absolute;
	inset: 0;
	overflow: auto;
}
</style>

// src/components/PanelGrid/PanelGrid.tsx
import React from 'react';
import './PanelGrid.css';

interface PanelGridProps {
  /**
   * Should only be passed `PanelGridItem` components.
   */
  children: React.ReactNode;
  /**
   * Makes the first panel sized properly for a sidebar.
   * Doesn't require any additional markup on the sidebar panel.
   */
  sidebarred?: boolean;
  className?: string;
}

export const PanelGrid = ({
  children,
  className = '',
  sidebarred = false,
}: PanelGridProps) => (
  <div className={`panel-grid ${sidebarred ? 'sidebarred' : ''} ${className}`.trim()}>
    {children}
  </div>
);
