// src/components/Panel/PanelBody.vue
<script setup lang="ts">
interface PanelBodyProps {
	className?: string;
	padded?: boolean;
}

const { className = '', padded = true } = defineProps<PanelBodyProps>();
</script>

<template>
	<div
		:class="
			`panel-body ${padded ? 'panel-body--padded' : ''} ${className}`.trim()
		"
	>
		<slot></slot>
	</div>
</template>

// oldSrc/components/Panel/PanelBody.tsx
import React from 'react';

interface PanelBodyProps {
	children: React.ReactNode;
	/**
	 * Controls whether the panel body has internal padding.
	 */
	padded?: boolean;
	className?: string;
}

export const PanelBody = ({
	children,
	className = '',
	padded = true,
}: PanelBodyProps) => (
	<div
		className={`panel-body ${padded ? 'panel-body--padded' : ''} ${className}`.trim()}
	>
		{children}
	</div>
);
