// packages/components/src/components/AppBanner.vue
<script setup lang="ts">
import { useKeycloak } from '@dsb-norge/vue-keycloak-js';
import { useRoute } from 'vue-router';
import CustomButton from './CustomButton.vue';
import { getLogger } from '@pdc/utilities';

const logger = getLogger('<AppBanner>');

const { authenticated, loginFn } = useKeycloak();
const route = useRoute();

const isHomePage = route.path === '/';
const showBanner = !authenticated && !isHomePage;

const handleLogin = async (): Promise<void> => {
	await loginFn?.().catch(logger.error);
};
</script>

<template>
	<div v-if="showBanner" class="App-banner">
		You are viewing limited public data.
		<CustomButton link-style @click="handleLogin">
			Log in to view more.
		</CustomButton>
	</div>
</template>

// oldSrc/components/AppBanner.tsx
import { useLocation } from 'react-router-dom';
import { useOidc } from '@axa-fr/react-oidc';
import { Button } from './Button';
import { getLogger } from '../logger';

const logger = getLogger('<AppBanner>');

const AppBanner = () => {
	const location = useLocation();
	const { isAuthenticated, login } = useOidc();

	const isHomePage = location.pathname === '/';
	const showBanner = !isAuthenticated && !isHomePage;

	return showBanner ? (
		<div className="App-banner">
			You are viewing limited public data.{' '}
			<Button
				linkStyle
				onClick={() => {
					login(location.pathname).catch(logger.error);
				}}
			>
				Log in to view more.
			</Button>
		</div>
	) : null;
};

export { AppBanner };
