// src/components/ListTable.vue
<script setup lang="ts" generic="T">
import {
	ColumnHead,
	TableComponent,
	TableBody,
	TableHead,
	TableRow,
} from './Table';

interface ListTableProps<T> {
	columns: string[];
	fieldNames?: Record<string, string>;
	items: T[];
	wrap?: boolean;
}
const {
	columns,
	items,
	fieldNames = undefined,
	wrap = false,
} = defineProps<ListTableProps<T>>();
</script>

<template>
	<TableComponent :truncate="!wrap">
		<TableHead fixed>
			<TableRow>
				<ColumnHead v-for="shortCode in columns" :key="shortCode">
					{{ fieldNames ? fieldNames[shortCode] : shortCode }}
				</ColumnHead>
			</TableRow>
		</TableHead>
		<TableBody><slot v-for="item in items" :item="item"></slot></TableBody>
	</TableComponent>
</template>

// src/components/ListTable.tsx
import React from 'react';
import { ColumnHead, Table, TableBody, TableHead, TableRow } from './Table';

interface ListTableProps<T> {
	columns: string[];
	fieldNames?: Record<string, string>;
	items: T[];
	wrap?: boolean;
	renderItem: (item: T) => React.ReactNode;
}

export const ListTable = <T,>({
	fieldNames = undefined,
	columns,
	items,
	renderItem,
	wrap = false,
}: ListTableProps<T>) => (
	<Table truncate={!wrap}>
		<TableHead fixed>
			<TableRow>
				{columns.map((shortCode) => (
					<ColumnHead key={shortCode}>
						{fieldNames ? fieldNames[shortCode] : shortCode}
					</ColumnHead>
				))}
			</TableRow>
		</TableHead>
		<TableBody>{items.map((item) => renderItem(item))}</TableBody>
	</Table>
);

export type { ListTableProps };
