// src/components/ListGrid/ListGrid.vue
<script setup lang="ts" generic="T">
import { ref, onMounted } from 'vue';
import type { ListGridProps } from './ListGridProps';

const { items } = defineProps<ListGridProps<T>>();

const listGridRef = ref<HTMLElement | null>(null);

function scrollToActiveItem() {
	const el = listGridRef.value?.querySelector('.active')
		?.previousElementSibling as HTMLElement | null;

	el?.scrollIntoView();
}
onMounted(scrollToActiveItem);
</script>

<template>
	<div ref="listGridRef">
		<slot v-for="item in items" :item="item"></slot>
	</div>
</template>

// src/components/ListGrid.tsx
import React, { useEffect } from 'react';

interface ListGridProps<T> {
	items: T[];
	renderItem(item: T): React.ReactNode;
}

export const ListGrid = <T,>({ items, renderItem }: ListGridProps<T>) => {
	const listGridRef = React.useRef<HTMLDivElement>(null);

	const scrollToActiveItem = () => {
		listGridRef.current
			?.querySelector('.active')
			?.previousElementSibling?.scrollIntoView();
	};

	useEffect(() => {
		scrollToActiveItem();
	}, []);

	return <div ref={listGridRef}>{items.map((item) => renderItem(item))}</div>;
};
