// src/components/ListTable.tsx
import React from 'react';
import { ColumnHead, Table, TableBody, TableHead, TableRow } from './Table';

interface ListTableProps<T> {
	columns: string[];
	fieldNames?: Record<string, string>;
	items: T[];
	wrap?: boolean;
	renderItem: (item: T) => React.ReactNode;
}

export const ListTable = <T,>({
	fieldNames = undefined,
	columns,
	items,
	renderItem,
	wrap = false,
}: ListTableProps<T>) => (
	<Table truncate={!wrap}>
		<TableHead fixed>
			<TableRow>
				{columns.map((shortCode) => (
					<ColumnHead key={shortCode}>
						{fieldNames ? fieldNames[shortCode] : shortCode}
					</ColumnHead>
				))}
			</TableRow>
		</TableHead>
		<TableBody>{items.map((item) => renderItem(item))}</TableBody>
	</Table>
);

export type { ListTableProps };

// packages/components/src/components/ListTable.vue
<template>
	<TableComponent :truncate="!wrap">
		<TableHead fixed>
			<TableRow>
				<ColumnHead v-for="column in columns" :key="column">
					{{ fieldNames?.[column] ?? column }}
				</ColumnHead>
			</TableRow>
		</TableHead>
		<TableBody>
			<template v-for="(item, index) in items" :key="index">
				<component :is="renderItem(item)" />
			</template>
		</TableBody>
	</TableComponent>
</template>

<script setup lang="ts" generic="T">
import {
	TableComponent,
	TableHead,
	TableBody,
	TableRow,
	ColumnHead,
} from './Table';

interface ListTableProps<T> {
	columns: string[];
	fieldNames?: Record<string, string>;
	items: T[];
	wrap?: boolean;
	renderItem: (item: T) => any; // Vue render function or component
}

const {
	fieldNames,
	columns,
	items,
	renderItem,
	wrap = false,
} = defineProps<ListTableProps<T>>();
</script>
