// oldSrc/components/Panel/PanelTag.tsx
import React from 'react';

interface PanelTagProps {
	children: React.ReactNode;
	icon?: React.ReactElement | null;
	badge?: string | null;
	className?: string;
}

export const PanelTag = ({
	children,
	icon = undefined,
	badge = undefined,
	className = '',
}: PanelTagProps) => (
	<div className={`panel-tag ${className}`.trim()}>
		{icon ? React.cloneElement(icon, { className: 'icon' }) : null}
		{badge ? <span className="badge">{badge}</span> : null}
		{children}
	</div>
);

// packages/components/src/components/Panel/PanelTag.vue
<script setup lang="ts">
import type { FunctionalComponent, HTMLAttributes, VNodeProps } from 'vue';

interface PanelTagProps {
	className?: string;
	icon?: FunctionalComponent<HTMLAttributes & VNodeProps>;
	badge?: string | null;
}

const {
	className = '',
	icon = undefined,
	badge = undefined,
} = defineProps<PanelTagProps>();
</script>

<template>
	<div :class="`panel-tag ${className}`.trim()">
		<component :is="icon" v-if="icon" />
		<span v-if="badge">
			{{ badge }}
		</span>
		<slot></slot>
	</div>
</template>
