// packages/components/src/components/Table/TableRow.vue
<script setup lang="ts">
export interface TableRowProps {
	className?: string;
	onClick?: () => void;
	active?: boolean;
}

const {
	className = '',
	onClick = undefined,
	active = false,
} = defineProps<TableRowProps>();
</script>

<template>
	<tr
		:class="
			`${className} ${onClick ? 'clickable' : ''} ${active ? 'active' : ''}`.trim()
		"
		@click="onClick"
	>
		<slot> </slot>
	</tr>
</template>

// oldSrc/components/Table/TableRow.tsx
import React from 'react';

interface TableRowProps {
	children: React.ReactNode;
	className?: string;
	onClick?: () => void;
	active?: boolean;
}

export const TableRow = ({
	children,
	className = '',
	onClick = undefined,
	active = false,
}: TableRowProps) => (
	<tr
		className={`${className} ${onClick ? 'clickable' : ''} ${active ? 'active' : ''}`.trim()}
		onClick={onClick}
	>
		{children}
	</tr>
);
