// packages/components/src/components/Table/TableHead.vue
<script setup lang="ts">
interface TableHeadProps {
	className?: string;
	fixed?: boolean;
}

const { className = '', fixed = false } = defineProps<TableHeadProps>();
</script>

<template>
	<thead :class="`${fixed ? 'fixed' : ''} ${className}`.trim()">
		<slot> </slot>
	</thead>
</template>

<style scoped>

</style>

// oldSrc/components/Table/TableHead.tsx
import React from 'react';

interface TableHeadProps {
	children: React.ReactNode;
	className?: string;
	fixed?: boolean;
}

export const TableHead = ({
	children,
	className = '',
	fixed = false,
}: TableHeadProps) => (
	<thead className={`${fixed ? 'fixed' : ''} ${className}`.trim()}>
		{children}
	</thead>
);
