// src/components/Table/ColumnHead.vue
<script setup lang="ts">
interface ColumnHeadProps {
	className?: string;
	actions?: boolean;
	actionAlignment?: 'left' | 'right';
}

const {
	className = '',
	actions = false,
	actionAlignment = 'right',
} = defineProps<ColumnHeadProps>();
</script>

<template>
	<th
		:class="
			`
    ${className}
    ${actions ? `has-actions action-alignment--${actionAlignment}` : ''}
  `.trim()
		"
	>
		<div class="column-head-wrapper">
			<slot> </slot>
		</div>
	</th>
</template>

// src/components/Table/ColumnHead.tsx
import React from 'react';

interface ColumnHeadProps {
  children?: React.ReactNode;
  className?: string;
  actions?: boolean;
  actionAlignment?: 'left' | 'right';
}

export const ColumnHead = ({
  children = null,
  className = '',
  actions = false,
  actionAlignment = 'right',
}: ColumnHeadProps) => (
  <th className={`
    ${className}
    ${actions ? `has-actions action-alignment--${actionAlignment}` : ''}
  `.trim()}
  >
    <div className="column-head-wrapper">
      {children}
    </div>
  </th>
);
