// src/components/Table/ColumnAction.tsx
import React from 'react';

interface ColumnActionProps {
  children: React.ReactNode;
  className?: string;
  title?: string;
  onClick?: () => void;
}

export const ColumnAction = ({
  children,
  className = '',
  title = '',
  onClick = () => null,
}: ColumnActionProps) => (
  <button
    type="button"
    onClick={onClick}
    className={`column-action ${className}`.trim()}
    title={title}
  >
    {children}
  </button>
);

// packages/components/src/components/Table/ColumnAction.vue
<script setup lang="ts">
interface ColumnActionProps {
	className?: string;
	title?: string;
	onClick?: () => void;
}

const {
	className = '',
	title = '',
	onClick = () => null,
} = defineProps<ColumnActionProps>();
</script>

<template>
	<button
		type="button"
		:class="`column-action ${className}`.trim()"
		:title="title"
		@click="onClick"
	>
		<slot> </slot>
	</button>
</template>
